### ISSUE TITLE
Appearance Issue

### ISSUE THREAD

**Issue by jsbarroso** [unruhschuh/TeXstudio.AppImage#3]
Hello!
I'm using the AppImage of TeXstudio 2.12 and can't change the appearance of the gui
When I run it, the appearance is not the dark one.
So I tried to change that in Options -> Configure TeXstudio -> General -> Appearance -> Style, but all of them look the same with the color scheme "Modern".
Is that a bug?

PS: I don't know if this is the right place to inform that, if it is not then excuse me

**Comment by unruhschuh** [comment]
During the build process, I'm patching the source to always use fusion style. This is necessary, since otherwise we would have to rely on the system to provide the proper style, which is not always the case. My primary goal is to make the program run on most systems. There might be a way to include the styles in the AppImage, but I don't see the urgency to do so, since I don't care about how the program looks as long as it is functional.

**Comment by jsbarroso** [comment]
On my OS (Ubuntu 16.04) it is a problem because any description text that appears when I hover on with the mouse pointer has background and text colors almost the same, so it's very hard to read.
Even though, I understand it's not a major issue as I can use the most of the TeXStudio. Thank you for the reply.
